[package]
org = "gha-indie-worker"
name = "gha-indie-worker-lib-core"
version = "0.1.0"
kind = "lib"
language = "rust"

[dependencies]
"gha-indie-worker/gha-indie-worker-interfaces" = "^0.1.0"
"oresoftware/ores-rpc-calls-http-tcp-pool" = "^0.1.0"
"oresoftware/ores-locks-and-leases" = "=0.1.1"
"oresoftware/k8s-libs-and-shared-defs" = "^0.1.0"
"declarative-migrations/declarative-migrations" = "^0.1.0"
"oresoftware/next-loggers-rust" = "^0.1.0"
