#![forbid(unsafe_code)]

//! Runtime validation of contract documents.
//!
//! JSON Schema is the runtime authority in this fleet (TypeSpec is its
//! independent peer at authoring time, but nothing parses `.tsp` at runtime), so
//! this module is what a server actually calls before it trusts a body, a frame
//! or a sync envelope.
//!
//! * [`json_schema`] — the validator over the fixed subset, pure Rust.
//! * [`pattern`] — the pattern matcher it uses, also pure Rust.
//! * `generated/` — regenerated by the lane from **both** authorities and
//!   byte-compared; see its README.
//!
//! ```
//! use gha_indie_worker_lib_core::validation::{validate, Violation};
//! use serde_json::json;
//!
//! let schema = json!({ "type": "object", "required": ["id"], "additionalProperties": false,
//!                      "properties": { "id": { "type": "string", "format": "uuid" } } });
//! let bad = json!({ "id": "nope" });
//! let violations: Vec<Violation> = validate(&schema, &bad).unwrap_err();
//! assert_eq!(violations[0].rule, "format");
//! ```

pub mod json_schema;
pub mod pattern;

pub use json_schema::{validate, validate_def, Violation};
pub use pattern::Pattern;

/// Render violations as the `ProblemViolation` rows the errors contract carries.
///
/// The tuple is `(pointer, rule, message)`, matching
/// `contracts/json-schema/errors.schema.json`. Callers assemble the RFC 9457
/// `Problem` around them; this crate deliberately does not know about HTTP.
#[must_use]
pub fn as_problem_violations(violations: &[Violation]) -> Vec<(String, String, String)> {
    violations
        .iter()
        .map(|v| (v.pointer.clone(), v.rule.to_owned(), v.message.clone()))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn violations_map_onto_the_errors_contract() {
        let schema = json!({ "type": "object", "required": ["id"] });
        let violations = validate(&schema, &json!({})).unwrap_err();
        let rows = as_problem_violations(&violations);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].0, "/id");
        assert_eq!(rows[0].1, "required");
    }
}
