#!/bin/sh
# Sync the generated contract artifacts from gha-indie-worker-interfaces into
# src/validation/generated/.
#
#   scripts/sync-validators.sh [path-to-interfaces-checkout]
#
# Refuses to copy anything unless the ores-contracts receipt for a slice says
# `status: passed` — which is the statement that the TypeSpec lane and the JSON
# Schema lane emitted identical bytes. Neither authority is generated from the
# other; a disagreement is a finding, and this script stops rather than picking
# a winner.
#
# The runner lane calls this after `node scripts/contracts-slices.mjs generate`
# in the interfaces checkout. It is never run at build time.
set -eu

here=$(cd "$(dirname "$0")/.." && pwd)
interfaces=${1:-${GHA_INDIE_WORKER_INTERFACES_DIR:-$here/../gha-indie-worker-interfaces}}
out=$here/src/validation/generated

if [ ! -d "$interfaces/contracts" ]; then
  echo "[sync-validators] no interfaces checkout at $interfaces" >&2
  echo "[sync-validators] pass the path, or set GHA_INDIE_WORKER_INTERFACES_DIR" >&2
  exit 2
fi

slices=$(node -e 'process.stdout.write(require(process.argv[1]).slices.join(" "))' \
  "$interfaces/contracts.config.json")

copied=0
for slice in $slices; do
  receipt=$interfaces/generated/$slice/receipt.json
  types=$interfaces/generated/$slice/rust/types.rs
  if [ ! -f "$receipt" ]; then
    echo "[sync-validators] $slice: no receipt — run 'npm run contracts:generate' in the interfaces checkout" >&2
    exit 3
  fi
  status=$(node -e 'process.stdout.write(require(process.argv[1]).status)' "$receipt")
  if [ "$status" != "passed" ]; then
    echo "[sync-validators] $slice: receipt status is '$status', refusing to sync" >&2
    echo "[sync-validators] the two authorities disagree; resolve the finding first" >&2
    exit 4
  fi
  if [ ! -f "$types" ]; then
    echo "[sync-validators] $slice: receipt passed but $types is missing" >&2
    exit 5
  fi
  mkdir -p "$out"
  {
    echo "// GENERATED by ores-contracts from BOTH authorities (parity-checked) — do not edit."
    echo "// Source: gha-indie-worker-interfaces/generated/$slice/rust/types.rs"
    echo "// Regenerate with: scripts/sync-validators.sh <interfaces-checkout>"
    cat "$types"
  } > "$out/$slice.rs"
  copied=$((copied + 1))
done

echo "[sync-validators] synced $copied slices into $out"
echo "[sync-validators] remember: src/validation/json_schema.rs and pattern.rs are hand-written and are NOT touched"
